// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Notes.API;

namespace Notes.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Notes.API.Models.Entities.APIKey", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.HasKey("ID");

                    b.ToTable("APIKey");
                });

            modelBuilder.Entity("Notes.API.Models.Entities.Note", b =>
                {
                    b.Property<Guid>("NoteID")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("APIKeyID");

                    b.Property<DateTimeOffset>("CreateDateTime");

                    b.Property<DateTimeOffset?>("LatestEditDateTime");

                    b.Property<string>("NoteContent")
                        .IsRequired()
                        .HasMaxLength(3000);

                    b.Property<string>("NoteTitle")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("NoteID");

                    b.HasIndex("APIKeyID");

                    b.ToTable("Note");
                });

            modelBuilder.Entity("Notes.API.Models.Entities.Note", b =>
                {
                    b.HasOne("Notes.API.Models.Entities.APIKey", "APIKey")
                        .WithMany()
                        .HasForeignKey("APIKeyID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
